### ISSUE TITLE
Update Shader system

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#116]
We should update our shader system by using `VtkShaderProperty` and `vtkShaderProgram` and not anymore the mapper

**Comment by dmreagan** [comment]
I agree, since it appears that this system allows you to share shader customizations across different mappers. I think `vtkShaderProperty` came in with VTK 8.2.0, so FURY will need a VTK version bump. 

[This example](https://lorensen.github.io/VTKExamples/site/Cxx/Shaders/SpatterShader/) may help with the transition, as it shows both the old way and the new.

**Comment by skoudoro** [comment]
Thanks @dmreagan! I think we should request a VTK PyPI package for 8.2 because it is not currently available.

**Comment by skoudoro** [comment]
Waiting for the new PyPI version...
