### ISSUE TITLE
Discord icon should appear in doc too

### ISSUE THREAD

**Issue by Garyfallidis** [fury-gl/fury#313]
See here: https://fury.gl/latest/community.html Discord icon is missing.

**Comment by tushar5526** [comment]
I'll do it :P

**Comment by skoudoro** [comment]
Great 👌! Just wait for October 1rst ;-)

**Comment by tushar5526** [comment]
Discord's icon is available from Font-Awesome 5, and vispy is using  4.3.0. 
For FA 5 you need a kit code by FA after signing up on their website [here](https://www.w3schools.com/icons/fontawesome5_intro.asp). So should I use my mail for the code?
Another option is to host FA 5 along with the website and then use it,but that's not necessary.

**Comment by dmreagan** [comment]
We should be able to upgrade to the free version of FA5 without signing up for a kit code by using one of the big CDNs like [cdnjs](https://cdnjs.com/libraries/font-awesome), [jsdelivr](https://www.jsdelivr.com/package/npm/@fortawesome/fontawesome-free), or [unpkg](https://unpkg.com/@fortawesome/fontawesome-free).

One thing to look for is whether you can pull in just the specific icons we need, or just the brand package, instead of all the icons.

**Comment by tushar5526** [comment]
Thank you @dmreagan for the heads up!
