### ISSUE TITLE
Track and fix warnings during tests. 

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#317]
When you run FURY tests, a bunch of warnings is popping up. The goal of this task is to track and fix them. Some of them are expected, others not. We will need many PR for this issue and more precisely, 1PR per module

TODO:
-------

- [x] fury/actor.py  (`pytest -svv fury/test_actor.py`)
- [x] fury/colormap.py  (`pytest -svv fury/test_colormap.py`)
- [x] fury/convert.py  (`pytest -svv fury/test_convert.py`)
- [x] fury/decorators.py  (`pytest -svv fury/test_decorators.py`)
- [x] fury/interactor.py  (`pytest -svv fury/test_interactor.py`)
- [x] fury/io.py  (`pytest -svv fury/test_io.py`)
- [ ] fury/layout.py  (`pytest -svv fury/test_layout.py`)
- [x] fury/ui.py  (`pytest -svv fury/test_ui.py`)
- [x] fury/pick.py  (`pytest -svv fury/test_pick.py`)
- [x] fury/primitive.py  (`pytest -svv fury/test_primitive.py`)
- [x] fury/transform.py  (`pytest -svv fury/test_transform.py`)
- [x] fury/window.py  (`pytest -svv fury/test_window.py`)
- [x] fury/utils.py  (`pytest -svv fury/test_utils.py`)

**Comment by tushar5526** [comment]
```
interactive = False

    def test_superquadric_actor(interactive=False):
        scene = window.Scene()
        centers = np.array([[8, 0, 0], [0, 8, 0], [0, 0, 0]])
        colors = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
        directions = np.random.rand(3, 3)
        scales = [1, 2, 3]
        roundness = np.array([[1, 1], [1, 2], [2, 1]])
    
        sq_actor = actor.superquadric(centers, roundness=roundness,
                                      directions=directions,
                                      colors=colors.astype(np.uint8),
                                      scales=scales)
        scene.add(sq_actor)
        if interactive:
            window.show(scene)
    
        arr = window.snapshot(scene, offscreen=True)
        arr[arr > 0] = 255  # Normalization
        report = window.analyze_snapshot(arr, colors=255*colors.astype(np.uint8))
>       npt.assert_equal(report.objects, 3)
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: 6
E        DESIRED: 3

fury/tests/test_actors.py:1290: AssertionError

```
Superquadratic actor is failing on my system, can anyone confirm this ?

**Comment by skoudoro** [comment]
I confirm, it is failing quite ramdomly,  so we need to improve the test and make it more robust

**Comment by Nibba2018** [comment]
@skoudoro I would like to work on `ui.py`

**Comment by skoudoro** [comment]
go ahead @Nibba2018! I will work on `utils`

**Comment by Nibba2018** [comment]
@skoudoro , 
```bash
DeprecationWarning: Converting `np.character` to a dtype is deprecated. The current result is `np.dtype(np.str_)` which is not strictly correct. Note that `np.character` is generally deprecated and 'S1' should be used.
```
seems to be a very common warning for all the tests. After digging I have found that this warning is being raised at `vtk.util.numpy_support.get_vtk_array_type`. Here the numpy array is said to have character value but I haven't noticed any character values in the array.

**Comment by skoudoro** [comment]
maybe we should just set up pytest to ignore this specific warning: https://docs.pytest.org/en/stable/warnings.html

Also, we should do it for the whole project...

**Comment by tushar5526** [comment]
I was going through `test_utils.py` and `test_pick.py` and it seems the warning is due to the `vtk` package,  not by something in fury. So in this case should I just add a skip in the pytest rules files?

**Comment by Nibba2018** [comment]
@tushar5526 These warnings are supposed to be generated by `vtk` and other dependencies but we need to understand the reason behind it and try to solve it accordingly.

**Comment by skoudoro** [comment]
from master branch, on `test_utils.py`, the warnings are:

```
fury/tests/test_utils.py::test_trilinear_interp
fury/tests/test_utils.py::test_trilinear_interp
  /Users/koudoro/Software/fury/fury/tests/test_utils.py:133: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
    x0 = x_indices.astype(np.integer)

fury/tests/test_utils.py::test_trilinear_interp
fury/tests/test_utils.py::test_trilinear_interp
  /Users/koudoro/Software/fury/fury/tests/test_utils.py:134: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
    y0 = y_indices.astype(np.integer)

fury/tests/test_utils.py::test_trilinear_interp
fury/tests/test_utils.py::test_trilinear_interp
  /Users/koudoro/Software/fury/fury/tests/test_utils.py:135: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
    z0 = z_indices.astype(np.integer)
``` 

It is not due to `vtk` package,  I do not understand your question @tushar5526?

**Comment by tushar5526** [comment]
I am using the command `pytest -svv fury/tests/test_utils.py` and the warnigs are different than of @skoudoro.
```
============================================================================ warnings summary ============================================================================
fury/tests/test_utils.py::test_polydata_lines
fury/tests/test_utils.py::test_polydata_polygon
fury/tests/test_utils.py::test_rotate
fury/tests/test_utils.py::test_vertices_from_actor
fury/tests/test_utils.py::test_get_actor_from_primitive
  /home/tushar55/.virtualenvs/fury/lib/python3.6/site-packages/vtk/util/numpy_support.py:137: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
    assert not numpy.issubdtype(z.dtype, complex), \

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================================================================== 16 passed, 5 warnings in 0.62s =====================================================================

```
It is saying there are 5 warnings, but pytest is not displaying them.
What command are you using @skudoro to get these warnings?

**Comment by skoudoro** [comment]
> What command are you using @skudoro to get the warnings you mentioned above?

I am using vtk 9.0.1. what is your VTK, fury,  numpy version ? Are you working with master branch ?

> It is saying there are 5 warnings, but pytest is not displaying them.

This is 5 times the same warning so pytest shows it only one time the warning and all the function that generated it above

**Comment by tushar5526** [comment]
Updating the packages worked. 
Thank you @skoudoro

**Comment by satishhhh** [comment]
@skoudoro is this issue still open for the remaining tests?

**Comment by skoudoro** [comment]
Hi @satishhhh,

I suppose so, you will need to run the tests to check if some warnings pop up.

**Comment by satishhhh** [comment]
@skoudoro  i would like to work on colormap.py

**Comment by amitchaudhari9121** [comment]
I'm working on `pytest -svv fury/tests/test_actors.py`, since no one else was...
---
@skoudoro 
I will share what I've discovered about test_actors.py, 
- most warnings are from the modules `dipy` and `vtkmodule` (vtk) 
- most warnings are repetitive, i went ahead and changed `pytest.ini` on my local machine to show every repetitive warning only once. and the number dropped from 60k\~ish to some 135\~ish [Pytest warnings filter  DOCS](https://docs.python.org/3/library/warnings.html#the-warnings-filter)
- Most of these warnings are mentioning the use of  deprecated `np.data_type`, where using just `data-type` would suffice. 

Note: (*Most* of the warnings) we should not be careless here. we should not assume that *all* warnings are about `np.data_type`

I'm trying to find if any of those 135 warnings are expected warnings , if they'll break something, or they're just deprecation warnings. 

PS: I'd like to know what breaking changes are we facing for vtk dependency. their [changelog](https://vtk.org/Wiki/VTK/API_Changes_8_2_0_to_9_0_0#Public_methods_removed_from_version_v8.2.0) is way too big for me to investigate. If I could get some assistance, I'd like to refactor the code to work with vtk 9.0.0

**Comment by satishhhh** [comment]
for vtk dependency error use vtk > 9.0.0  use commond pip install vtk>9.0.0 
and if the issue is not resolved then the problem would be in the python version use python 3.8 or 3.7 and use 64 bit operating system.

**Comment by amitchaudhari9121** [comment]
> for vtk dependency error use vtk > 9.0.0 use commond pip install vtk>9.0.0

NO, 
please look into [how versions are named](https://semver.org/), doing what you say will almost surely break the code in some way or other. 

The correct way about going around is to look at where we are using vtk and which methods are we using. if those methods are breaking our code, we try to refactor our code to not use that particular method... **This is what I need help with**

We do that refactoring, then our code works on 9.0.0 and sub sequent releases... only then should we introduce 9.0.0 into our requirements.

> and if the issue is not resolved then the problem would be in the python version use python 3.8 or 3.7 and use 64 bit
operating system. Hoping it will solve the dependency issue

I'm not sure about why you wrote this.

Thanks for looking into this though :)
Appreciate it.

**Comment by skoudoro** [comment]
@amitchaudhari9121, 

Thank you for looking into this. The code works without any problem with VTK 9.0.0. We skip this version because VTK introduces a bug in their thread / multicore management. 
It is not recommended to use this version and that's why they created the 9.0.1.

I will look at your PR when I find time.

**Comment by amitchaudhari9121** [comment]
After the Recent commit #396 ,
These tests no longer give any warnings:
- test_colormap.py `pytest -svv fury/tests/test_colormap.py `
- test_decorators.py `pytest -svv fury/tests/test_decorators.py `
- test_interactor.py `pytest -svv fury/tests/test_interactor.py` (this needs introspection?)
- test_io.py `pytest -svv fury/tests/test_io.py` (it skipped a test due to my OSX confilct)
- test_ui.py `pytest -svv fury/tests/test_ui.py`
- test_pick.py `pytest -svv fury/tests/test_pick.py`
- test_primitive.py `pytest -svv fury/tests/test_primitive.py`
- test_window.py `pytest -svv fury/tests/test_window.py`
- test_transform.py `pytest -svv fury/tests/test_transform.py`

I'll like to work on the remaining ones, which are: 
- test_utils.py (Its just one warning TBH, I'll try to summarize what it is below)
  - `np.integer` conversion to `np.signedinteger` might not give stable results, better to change to `np.int32` or `np.int64` for stability. (This warning is repeated for 3 axes, mentioned 2 times, making 6 warnings in total. but its only one warning in essence)
Notes: 
- There's no `test_convert.py`(there's `convert.py`, but it's got no tests) but it's mentioned in the initial comment. I think it was a typo, need help, are tests remaining for it? (if yes, I'd like to help create them)
- Could not find `test_layout.py`. need help, are tests remaining for it?(me like to contribute :) )
---

Please confirm and update this issue's description (or the first comment :)  )

**Comment by skoudoro** [comment]
Hi @amitchaudhari9121,

Thank you for the overview. Indeed, I confirm that all the tests cited above are OK.

- You can work on `test_utils.py`. I will look into it in your PR to confirm your conclusion
- Yes, feel free to create tests for `convert.py` module!
- Yes, feel free to create tests for `test_layout.py` module!
- Also, there is 1 last warning to fix in test_actor.py 
```python
DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
    flags[i] = np.any(np.any(np.all(im[..., :3] == col[:3], axis=-1)))
```

You can fix all this in one PR, no problem, just make sure to split each commit. 4 commits should be ideal.

Thank you very much for looking into this.
