### ISSUE TITLE
GLTF 2.0

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#82]
[here](https://blog.kitware.com/introducing-gltf-2-0-support-in-vtk-and-paraview/) some good news about GLTF 2.0 that we need to study and play with.
Potential use for a dynamic scene on our documentation.

**Comment by dmreagan** [comment]
This doesn't really give any new functionality, since if we want live vtk.js demos on the site we can do that already by [loading .vtk files](https://kitware.github.io/vtk-js/examples/PolyDataReader.html) (or other [already](https://kitware.github.io/vtk-js/examples/STLReader.html)-[supported](https://kitware.github.io/vtk-js/examples/OBJReader.html) 3D formats). However, glTF is supposed to be a superior format for delivering 3D content on the web (marketed as the JPEG of 3D), so it is indeed a small step forward. 

Plus @skoudoro is excited since glTF support was implemented by the Kitware France team! :fr:

**Comment by skoudoro** [comment]
> Plus @skoudoro is excited since glTF support was implemented by the Kitware France team! 

ahaha !!!  😄 

I find it interesting because of the animation/interaction.  To tell you the truth @dmreagan, I do not know if you can save an interaction/animation on a vtk file and then replay it on vtkjs. Let's see. I need to find time to try it.

**Comment by skoudoro** [comment]
integrated 🥳 . closing
